BEGIN;
ALTER TABLE IIS.BN_HITS_STAGE ADD COLUMN USER_AGENT VARCHAR;
ALTER TABLE IIS.BN_HITS ADD COLUMN USER_AGENT VARCHAR;
ALTER TABLE IIS.BN_HITS_SP ADD COLUMN USER_AGENT VARCHAR;
ALTER TABLE IIS.BN_SESSION ADD COLUMN USER_AGENT VARCHAR;
ALTER TABLE IIS.BN_SESSION_STAGE ADD COLUMN USER_AGENT VARCHAR;
ALTER TABLE IIS.BN_SESSION_UPDATE_STAGE ADD COLUMN USER_AGENT VARCHAR;
ALTER TABLE IIS.CLICK_SEARCHES ADD COLUMN USER_AGENT VARCHAR;
END;

